name: Android CI

on:
  pull_request:

jobs:

  tests:
    runs-on: macOS-latest
    timeout-minutes: 40
    env:
      ORG_GRADLE_PROJECT_SERVICE_ACCOUNT_FILE_PATH: ${{ secrets.TEMPO_SERVICE_ACCOUNT_FILE_PATH }}
      ORG_GRADLE_PROJECT_KEY_STORE_FILE_PATH: ${{ secrets.TEMPO_KEY_STORE_FILE_PATH }}
      ORG_GRADLE_PROJECT_KEY_STORE_PASSWORD: ${{ secrets.TEMPO_KEY_STORE_PASSWORD }}
      ORG_GRADLE_PROJECT_KEY_ALIAS: ${{ secrets.TEMPO_KEY_ALIAS }}
      ORG_GRADLE_PROJECT_KEY_ALIAS_PASSWORD: ${{ secrets.TEMPO_KEY_ALIAS_PASSWORD }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant permissions
        run: |
          chmod +x ./scripts/decrypt_secrets.sh
          chmod +x ./scripts/clean_secrets.sh
          chmod +x ./gradlew

      - name: Decrypt secrets
        run: ./scripts/decrypt_secrets.sh
        env:
          ENCRYPT_KEY: ${{ secrets.TEMPO_ENCRYPT_KEY }}

#      - name: Build project
#        run: ./gradlew assembleDebug --stacktrace

      - name: Run unit-tests
        run: ./gradlew testDebug

      - name: Run instrument-tests
        uses: reactivecircus/android-emulator-runner@v2.28.0
        with:
          api-level: 29
          script: ./gradlew connectedDebugAndroidTest

      - name: Clean secrets
        if: always()
        run: ./scripts/clean_secrets.sh
